# Generated by Django 3.0.3 on 2020-03-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20200312_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follower',
        ),
        migrations.AddField(
            model_name='followers',
            name='followers',
            field=models.ManyToManyField(related_name='follower', to='user_profile.User'),
        ),
        migrations.RemoveField(
            model_name='following',
            name='following',
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ManyToManyField(related_name='follow', to='user_profile.User'),
        ),
    ]
