# Generated by Django 3.0.3 on 2020-03-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200312_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followers',
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.ManyToManyField(related_name='i_follow', to='user_profile.User'),
        ),
        migrations.AlterField(
            model_name='following',
            name='following',
            field=models.ManyToManyField(related_name='follow_me', to='user_profile.User'),
        ),
    ]
