# Generated by Django 3.0.3 on 2020-03-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20200315_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ManyToManyField(related_name='follow_you', to='user_profile.User'),
        ),
    ]
