# Generated by Django 3.0.3 on 2020-03-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20200315_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ManyToManyField(related_name='follower', to='user_profile.User'),
        ),
    ]
