# Generated by Django 3.0.3 on 2020-03-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_userfollowers_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFollowers',
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
