# Generated by Django 3.0.3 on 2020-03-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20200317_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/home/ojay/Downloads/user.png', upload_to='images'),
        ),
    ]
