# Generated by Django 3.0.3 on 2020-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20200319_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.png', upload_to='images'),
        ),
    ]
