# Generated by Django 3.0.3 on 2020-03-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200314_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='country',
        ),
    ]
