# Generated by Django 3.0.3 on 2020-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20200314_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_count',
            field=models.IntegerField(default=1),
        ),
    ]
