# Generated by Django 3.0.3 on 2020-03-20 09:18

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_hashtag_hashtag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images'),
        ),
    ]
