# Generated by Django 3.0.3 on 2020-03-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_file',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
