# Generated by Django 3.0.3 on 2020-03-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20200320_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
