# Generated by Django 3.0.3 on 2020-03-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_tweet_video_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='video_thumbnail_image',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
